
#
#          Variables
#


parameters:
  capacity_factor_min:
    description: Minimum capacity factor that a technology must achieve over the whole time horizon.
    default: 0

#
#          Constraints
#

constraints:
  annual_capacity_factor_min:
    description: >
      Limit the lower bound of annual technology operation as a
      fraction of annual operation at maximum capacity.
    foreach: [nodes, techs, carriers]
    where: capacity_factor_min
    equations:
      - expression: >
          sum(flow_out * timestep_weights, over=timesteps) / $total_time >= flow_cap * capacity_factor_min
    sub_expressions:
      total_time:
        - expression: >
            sum(timestep_resolution * timestep_weights, over=timesteps)

#
#          Global Expressions
#
